### ISSUE TITLE
Dependence on nightly

### ISSUE THREAD

**Issue by Roenbaeck** [prataprc/jsondata#18]
It looks like the following feature prevents the crate from compiling on stable Rust. 
```rust
#![feature(total_cmp)]
``` 
Is it possible to work around this feature in order to get the crate to compile on stable? If not, is there an expected time frame for when this feature might make it into stable? I would really like to use the crate, but the dependence on nightly could become an issue.

**Comment by prataprc** [comment]
This is the tracking issue - https://github.com/rust-lang/rust/issues/72599
Looks like there are concerns with regard to LLVM and processor (MIPS in this case, but I am not sure whether someone did an exhaustive study on all processors that exists today).

**Comment by prataprc** [comment]
Thanks for the reminder. It is stable indeed :)

Made a new release `0.8.1` that should be available for stable channel. Let me know if there is any problem. This issue can be closed.
